version: '3.0'

services:
  build-nilrt:
    build:
      context: .
      dockerfile: build-nilrt.Dockerfile
    environment:
      TERM: xterm-256color
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /mnt/workspace
    volumes:
      - ../../:/mnt/workspace  # the nilrt.git workspace
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
