#!/bin/sh
#
# Returns 1 if the current repo's tracking branch, or any submodule's tracking
# branch, has been updated remotely. Otherwise, returns 0.
#
# If submodules are employed, `git submodule init` and `git submodule update`
# must be run beforehand.


# Use "." to refer to PWD (i.e. parent repo)
check_repo () {
	branch=$(git rev-parse --abbrev-ref HEAD)
	remote=$(git config branch.$branch.remote)
	merge=$(git config branch.$branch.merge)

	if [ -n "$remote" -a -n "$merge" ]; then
		remoteid=$(git ls-remote "$remote" "$merge")
		localid=$(git rev-parse HEAD)
		mergeid=$(git merge-base "$remoteid" "$localid" 2>/dev/null)
		if [ "$mergeid" != "$remoteid" ]; then
			echo "."
		fi
	fi
}

check_submodules () {
	dist=$(dirname $(readlink -f $0))
	git submodule -q foreach ". $dist/check_source_foreach.sh"
}

changed="$(check_repo)$(check_submodules)"
[ -n "$changed" ] || exit 0
echo $changed
exit 1
